### ISSUE TITLE
git tags and docker hub tags don't match up

### ISSUE THREAD

**Issue by technicalpickles** [Gusto/buildkite-builder#123]
Here's git:

![CleanShot 2024-12-20 at 11 35 50](https://github.com/user-attachments/assets/b9d01474-9376-45ed-acf2-df5e8054e541)

And docker hub:

![CleanShot 2024-12-20 at 11 36 04](https://github.com/user-attachments/assets/3a928930-f150-4d0c-aae9-de946a41fbe9)

Mostly noticed this because the README has a pretty old version in the example, and I got the latest from git tag... and got an error about the manifest missing when trying to use it.

**Comment by ngan** [comment]
This was sort of by design. Tags can be whatever for sure, but I've noticed docker tags typically are just the version number without the `v`. (And git tags include `v`)

**Comment by technicalpickles** [comment]
Sorry I wasn't more clear. The problem isn't the `v` vs no v. It's that the newer releases of buildkite-builder no longer are tagged at all on 

We're only able to use the latest buildkite-builder because we are building our own image. Using the documented method of uploading a pipeline.yml would fail:

```
steps:
  - label: ":toolbox:"
    key: "buildkite-builder"
    agents:
      queue: "heavy"
    retry:
      automatic:
        - exit_status: -1 # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    plugins:
      - docker#v5.12.0:
          image: "gusto/buildkite-builder:4.16.0"
          propagate-environment: true
```

Because https://hub.docker.com/r/gusto/buildkite-builder/tags doesn't have any tags since 4.13
