### ISSUE TITLE
Consider installing as a Buildkite Plugin

### ISSUE THREAD

**Issue by ngan** [Gusto/buildkite-builder#16]
Currently, BKB can be installed a gem or a docker image (using the docker plugin). A third, and maybe preferable, method of installation can be a bonafide Buildkite plugin. We’d essentially be copying what the docker plugin does but it might look cleaner:

```
steps:
  - label: “:toolbox”
    plugins:
      - Gusto/buildkite-builder#v1.2
```

The only downside I can see to this is duplicating all functionally of the docker plugin here. It would be great if we can depend on that plugin and delegate to it somehow.
