### ISSUE TITLE
Docker Plugin Command

### ISSUE THREAD

**Issue by joshedney** [Gusto/buildkite-builder#54]
Hey,

I'm trying to replicate this section of a buildkite pipeline.yml

```    
plugins:
  docker-compose#v3.1.0:
    run: image
    command: ["command", "foo", "bar"]
 ```
 
But I'm having trouble replicating the `command: ["command", "foo", "bar"]` section.

Any tips on how I can do this ?
